INCDIR	= $(ROOTDIR)/include
LIBDIR	= $(ROOTDIR)/sys/lib

MAKE	= make
CC	= gcc
AR	= ar -r
RANLIB	= ranlib
LD	= ld
SIZE	= size
RM	= rm -f

CFLAGS	= -c -Wall -ffreestanding
CFLAGS += -m32

#
# PCI device support.  The _PCI definition enables scanning for PCI
# devices so that PCI device drivers can obtain information about them.
# This functionality does not work with the Bochs emulator and must
# be disabled to boot Roadrunner using Bochs.
#
CFLAGS += -D_PCI

INDENT_RULES = -nbad -bap -nbc -bbo -hnl -br -brs -c33 -cd33 -ncdb -ce -ci4 -cli0 -d0 -di1 -nfc1 -i8 -ip0 -l80 -lp -npcs -nprs -npsl -sai -saf -saw -ncs -nsc -sob -nfca -cp33 -ss -ts8 -il1

.S.o: $<
#	$(CC) $(CFLAGS) -nostdinc -I. -I- -I$(INCDIR) -o $@ $<
	$(CC) $(CFLAGS) -nostdinc -iquote . -I$(INCDIR) -o $@ $<

.c.o: $<
#	$(CC) $(CFLAGS) -nostdinc -I. -I- -I$(INCDIR) -o $@ $<
	$(CC) $(CFLAGS) -nostdinc -iquote . -I$(INCDIR) -o $@ $<
